import type { Tone } from "@/lib/games";

export type Difficulty = "easy" | "medium" | "hard";
export type DifficultySetting = Difficulty | "mix";

export interface QuizQuestion {
  q: string;
  a: string;
  d: Difficulty;
}

export interface QuizPack {
  id: string;
  label: string;
  tone: Tone;
  questions: QuizQuestion[];
}

/** Short questions with one clear answer. Easy enough to answer in seconds. */
export const quizPacks: QuizPack[] = [
  {
    id: "gen",
    label: "General knowledge",
    tone: "blue",
    questions: [
      { q: "What is the capital of Australia?", a: "Canberra", d: "easy" },
      { q: "How many sides does a hexagon have?", a: "Six", d: "easy" },
      { q: "Which planet is known as the Red Planet?", a: "Mars", d: "easy" },
      { q: "What is the chemical symbol for gold?", a: "Au", d: "easy" },
      { q: "What is the largest ocean on Earth?", a: "The Pacific", d: "easy" },
      { q: "How many continents are there?", a: "Seven", d: "easy" },
      { q: "What is the hardest natural substance?", a: "Diamond", d: "easy" },
      { q: "Who painted the Mona Lisa?", a: "Leonardo da Vinci", d: "easy" },
      { q: "What is the capital of Japan?", a: "Tokyo", d: "easy" },
      { q: "What gas do plants take in from the air?", a: "Carbon dioxide", d: "easy" },
      { q: "Which is the tallest animal?", a: "The giraffe", d: "easy" },
      { q: "At what temperature in Celsius does water boil?", a: "100", d: "easy" },
      { q: "What is the smallest prime number?", a: "Two", d: "easy" },
      { q: "Who wrote Romeo and Juliet?", a: "William Shakespeare", d: "easy" },
      { q: "How many days are in a leap year?", a: "366", d: "easy" },
      { q: "What is the largest planet in our solar system?", a: "Jupiter", d: "easy" },
      { q: "Which organ pumps blood around the body?", a: "The heart", d: "easy" },
      { q: "What is the fastest land animal?", a: "The cheetah", d: "easy" },
      { q: "What is the capital of Canada?", a: "Ottawa", d: "easy" },
      { q: "What is the square root of 144?", a: "12", d: "easy" },
      { q: "Which metal is liquid at room temperature?", a: "Mercury", d: "medium" },
      { q: "How many strings does a standard guitar have?", a: "Six", d: "easy" },
      { q: "Which country does pizza come from?", a: "Italy", d: "easy" },
      { q: "Who is said to have discovered gravity after an apple fell?", a: "Isaac Newton", d: "easy" },
      { q: "What is the largest mammal?", a: "The blue whale", d: "easy" },
      { q: "How many hours are in a week?", a: "168", d: "easy" },
      { q: "What is the capital of Egypt?", a: "Cairo", d: "easy" },
      { q: "Which language has the most native speakers?", a: "Mandarin Chinese", d: "medium" },
      { q: "What do bees make?", a: "Honey", d: "easy" },
      { q: "At what temperature in Fahrenheit does water freeze?", a: "32", d: "easy" },
      { q: "Who painted The Starry Night?", a: "Vincent van Gogh", d: "easy" },
      { q: "What is the capital of Brazil?", a: "Brasília", d: "medium" },
      { q: "How many bones are in an adult human body?", a: "206", d: "medium" },
      { q: "What is the largest hot desert in the world?", a: "The Sahara", d: "medium" },
      { q: "What is the capital of France?", a: "Paris", d: "easy" },
      { q: "What is the capital of Turkey?", a: "Ankara", d: "medium" },
      { q: "Which element has the atomic number 1?", a: "Hydrogen", d: "medium" },
      { q: "Who wrote the novel '1984'?", a: "George Orwell", d: "medium" },
      { q: "What is the smallest country in the world?", a: "Vatican City", d: "medium" },
      { q: "Who developed the theory of relativity?", a: "Albert Einstein", d: "medium" },
      { q: "What is the capital of Switzerland?", a: "Bern", d: "medium" },
      { q: "What is the powerhouse of the cell?", a: "The mitochondria", d: "medium" },
      { q: "Who painted the ceiling of the Sistine Chapel?", a: "Michelangelo", d: "medium" },
      { q: "What is the currency of Japan?", a: "The yen", d: "medium" },
      { q: "Which is the largest country by area?", a: "Russia", d: "medium" },
      { q: "What language is mainly spoken in Brazil?", a: "Portuguese", d: "medium" },
      { q: "What is the chemical symbol for sodium?", a: "Na", d: "medium" },
      { q: "Who was the first person to walk on the Moon?", a: "Neil Armstrong", d: "medium" },
      { q: "In which year did World War II end?", a: "1945", d: "medium" },
      { q: "What is the capital of South Korea?", a: "Seoul", d: "medium" },
      { q: "How many keys does a standard piano have?", a: "88", d: "medium" },
      { q: "What is the Roman numeral for 50?", a: "L", d: "medium" },
      { q: "What is the capital of Kazakhstan?", a: "Astana", d: "hard" },
      { q: "Which element has the chemical symbol W?", a: "Tungsten", d: "hard" },
      { q: "Who wrote 'One Hundred Years of Solitude'?", a: "Gabriel García Márquez", d: "hard" },
      { q: "What is the deepest known ocean trench called?", a: "The Mariana Trench", d: "hard" },
      { q: "Who composed 'The Four Seasons'?", a: "Antonio Vivaldi", d: "hard" },
      { q: "What is the currency of Thailand?", a: "The baht", d: "hard" },
      { q: "What is the SI unit of force?", a: "The newton", d: "hard" },
      { q: "In which year did the Berlin Wall fall?", a: "1989", d: "hard" },
      { q: "Who was the first woman to win a Nobel Prize?", a: "Marie Curie", d: "hard" },
      { q: "What is the capital of New Zealand?", a: "Wellington", d: "hard" },
      { q: "Who painted 'The Persistence of Memory'?", a: "Salvador Dalí", d: "hard" },
      { q: "What is the study of fungi called?", a: "Mycology", d: "hard" },
      { q: "What is the capital of Myanmar?", a: "Naypyidaw", d: "hard" },
    ],
  },
  {
    id: "india",
    label: "India",
    tone: "orange",
    questions: [
      { q: "What is the capital of India?", a: "New Delhi", d: "easy" },
      { q: "Who is known as the Father of the Nation in India?", a: "Mahatma Gandhi", d: "easy" },
      { q: "What is India's national animal?", a: "The tiger", d: "easy" },
      { q: "Which river is considered the holiest in India?", a: "The Ganga", d: "easy" },
      { q: "The Taj Mahal is in which city?", a: "Agra", d: "easy" },
      { q: "In which year did India become independent?", a: "1947", d: "easy" },
      { q: "What is India's national flower?", a: "The lotus", d: "easy" },
      { q: "Who was India's first Prime Minister?", a: "Jawaharlal Nehru", d: "easy" },
      { q: "Which is the largest Indian state by area?", a: "Rajasthan", d: "medium" },
      { q: "Which Indian state is famous for its backwaters?", a: "Kerala", d: "easy" },
      { q: "What is the currency of India?", a: "The rupee", d: "easy" },
      { q: "Who wrote the Indian national anthem?", a: "Rabindranath Tagore", d: "medium" },
      { q: "The Gateway of India is in which city?", a: "Mumbai", d: "easy" },
      { q: "Which festival is known as the festival of colours?", a: "Holi", d: "easy" },
      { q: "Which festival is known as the festival of lights?", a: "Diwali", d: "easy" },
      { q: "What is the capital of Karnataka?", a: "Bengaluru", d: "easy" },
      { q: "Which city is called the Pink City?", a: "Jaipur", d: "easy" },
      { q: "Which sea lies to the west of India?", a: "The Arabian Sea", d: "easy" },
      { q: "The Qutub Minar is in which city?", a: "Delhi", d: "easy" },
      { q: "How many states does India have?", a: "28", d: "easy" },
      { q: "What is the capital of Maharashtra?", a: "Mumbai", d: "easy" },
      { q: "Which is the highest mountain in India?", a: "Kanchenjunga", d: "medium" },
      { q: "Who was India's first woman Prime Minister?", a: "Indira Gandhi", d: "medium" },
      { q: "Which city is known as the 'City of Joy'?", a: "Kolkata", d: "medium" },
      { q: "The Konark Sun Temple is in which state?", a: "Odisha", d: "medium" },
      { q: "Who is known as the 'Missile Man of India'?", a: "A. P. J. Abdul Kalam", d: "medium" },
      { q: "Which Mughal emperor built the Taj Mahal?", a: "Shah Jahan", d: "medium" },
      { q: "In which year was the Jallianwala Bagh massacre?", a: "1919", d: "medium" },
      { q: "Which Indian mission landed near the Moon's south pole in 2023?", a: "Chandrayaan-3", d: "medium" },
      { q: "Which is the smallest Indian state by area?", a: "Goa", d: "medium" },
      { q: "Who was the first President of India?", a: "Dr Rajendra Prasad", d: "medium" },
      { q: "Which Indian city is called the 'Silicon Valley of India'?", a: "Bengaluru", d: "medium" },
      { q: "Who won India's first individual Olympic gold medal?", a: "Abhinav Bindra", d: "medium" },
      { q: "The ruins of Hampi are in which state?", a: "Karnataka", d: "medium" },
      { q: "What is the capital of Tamil Nadu?", a: "Chennai", d: "medium" },
      { q: "Who founded the Maurya Empire?", a: "Chandragupta Maurya", d: "hard" },
      { q: "Which 1757 battle began British rule in Bengal?", a: "The Battle of Plassey", d: "hard" },
      { q: "Who was the last Viceroy of India?", a: "Lord Mountbatten", d: "hard" },
      { q: "The Sanchi Stupa is in which state?", a: "Madhya Pradesh", d: "hard" },
      { q: "Which Indian shared the 2014 Nobel Peace Prize?", a: "Kailash Satyarthi", d: "hard" },
      { q: "Who wrote 'The Discovery of India'?", a: "Jawaharlal Nehru", d: "hard" },
      { q: "In which year did the Constitution of India come into effect?", a: "1950", d: "hard" },
      { q: "Which Indian physicist won the Nobel Prize in 1930?", a: "C. V. Raman", d: "hard" },
      { q: "Who wrote 'The God of Small Things'?", a: "Arundhati Roy", d: "hard" },
      { q: "Kaziranga National Park is in which state?", a: "Assam", d: "hard" },
      { q: "Who won India's first individual Olympic medal after independence, in 1952?", a: "K. D. Jadhav", d: "hard" },
    ],
  },
  {
    id: "pop",
    label: "Films & music",
    tone: "purple",
    questions: [
      { q: "Who played Jack in Titanic?", a: "Leonardo DiCaprio", d: "easy" },
      { q: "Which film features the line 'Kitne aadmi the?'", a: "Sholay", d: "easy" },
      { q: "Who is known as the King of Pop?", a: "Michael Jackson", d: "easy" },
      { q: "Which actor is nicknamed 'King Khan'?", a: "Shah Rukh Khan", d: "easy" },
      { q: "What is the name of Harry Potter's owl?", a: "Hedwig", d: "easy" },
      { q: "Which Disney film features a lion called Simba?", a: "The Lion King", d: "easy" },
      { q: "Who directed Jurassic Park?", a: "Steven Spielberg", d: "easy" },
      { q: "Which band sang 'Bohemian Rhapsody'?", a: "Queen", d: "easy" },
      { q: "Which cartoon character lives in a pineapple under the sea?", a: "SpongeBob SquarePants", d: "easy" },
      { q: "Who sang 'Shape of You'?", a: "Ed Sheeran", d: "easy" },
      { q: "In which film does Aamir Khan play wrestling coach Mahavir Phogat?", a: "Dangal", d: "easy" },
      { q: "Which Marvel hero wields a hammer?", a: "Thor", d: "easy" },
      { q: "What colour is Pikachu?", a: "Yellow", d: "easy" },
      { q: "Which TV show features Walter White?", a: "Breaking Bad", d: "easy" },
      { q: "Which Marvel hero is Tony Stark?", a: "Iron Man", d: "easy" },
      { q: "Which film features the song 'Chaiyya Chaiyya'?", a: "Dil Se", d: "medium" },
      { q: "Who directed the film 'Inception'?", a: "Christopher Nolan", d: "medium" },
      { q: "Which band recorded 'Hotel California'?", a: "The Eagles", d: "medium" },
      { q: "Who plays Captain Jack Sparrow?", a: "Johnny Depp", d: "medium" },
      { q: "Which South Korean film won Best Picture at the 2020 Oscars?", a: "Parasite", d: "medium" },
      { q: "Who composed the song 'Jai Ho'?", a: "A. R. Rahman", d: "medium" },
      { q: "Who directed the film 'Lagaan'?", a: "Ashutosh Gowariker", d: "medium" },
      { q: "Who played the Joker in 'The Dark Knight'?", a: "Heath Ledger", d: "medium" },
      { q: "What is Ross's job in 'Friends'?", a: "Palaeontologist", d: "medium" },
      { q: "Which singer was born Stefani Germanotta?", a: "Lady Gaga", d: "medium" },
      { q: "Who directed 'Sholay'?", a: "Ramesh Sippy", d: "medium" },
      { q: "Which film features the song 'Tum Hi Ho'?", a: "Aashiqui 2", d: "medium" },
      { q: "Which actress played the lead in 'Queen'?", a: "Kangana Ranaut", d: "medium" },
      { q: "In which TV show is Winterfell a castle?", a: "Game of Thrones", d: "medium" },
      { q: "Who directed 'Pulp Fiction'?", a: "Quentin Tarantino", d: "hard" },
      { q: "Which silent-era film won the first Best Picture Oscar?", a: "Wings", d: "hard" },
      { q: "Who recorded 'Like a Rolling Stone'?", a: "Bob Dylan", d: "hard" },
      { q: "Who directed 'Mother India' (1957)?", a: "Mehboob Khan", d: "hard" },
      { q: "What was India's first full-length talkie?", a: "Alam Ara", d: "hard" },
      { q: "Which Beatles album includes 'Come Together'?", a: "Abbey Road", d: "hard" },
      { q: "Who composed the score for 'Interstellar'?", a: "Hans Zimmer", d: "hard" },
      { q: "Who directed 'Pather Panchali'?", a: "Satyajit Ray", d: "hard" },
      { q: "In which Oscar category was 'Lagaan' nominated?", a: "Best Foreign Language Film", d: "hard" },
      { q: "Which band recorded 'Stairway to Heaven'?", a: "Led Zeppelin", d: "hard" },
    ],
  },
  {
    id: "sport",
    label: "Sport",
    tone: "green",
    questions: [
      { q: "How many players are in a cricket team?", a: "Eleven", d: "easy" },
      { q: "How many runs is a six worth in cricket?", a: "Six", d: "easy" },
      { q: "Which country won the 2011 Cricket World Cup?", a: "India", d: "easy" },
      { q: "In which sport is Wimbledon held?", a: "Tennis", d: "easy" },
      { q: "How many rings are on the Olympic flag?", a: "Five", d: "easy" },
      { q: "Which sport uses a shuttlecock?", a: "Badminton", d: "easy" },
      { q: "Which country won the 2022 FIFA World Cup?", a: "Argentina", d: "easy" },
      { q: "How many overs does each team get in a T20 match?", a: "20", d: "easy" },
      { q: "Which sport uses a puck?", a: "Ice hockey", d: "easy" },
      { q: "Who captained India to the 2011 World Cup win?", a: "MS Dhoni", d: "easy" },
      { q: "Which sport is Virat Kohli famous for?", a: "Cricket", d: "easy" },
      { q: "Which player is nicknamed the 'Master Blaster'?", a: "Sachin Tendulkar", d: "easy" },
      { q: "Where were the Olympic Games held in 2021?", a: "Tokyo", d: "easy" },
      { q: "How many players are on a football team on the pitch?", a: "Eleven", d: "easy" },
      { q: "Which country hosted the 2018 FIFA World Cup?", a: "Russia", d: "medium" },
      { q: "How many players per side are on court in basketball?", a: "Five", d: "medium" },
      { q: "Which team won the first Cricket World Cup in 1975?", a: "West Indies", d: "medium" },
      { q: "Who won javelin gold for India at Tokyo 2020?", a: "Neeraj Chopra", d: "medium" },
      { q: "What is the term for taking three wickets in three balls?", a: "A hat-trick", d: "medium" },
      { q: "Which Grand Slam tennis tournament is played on clay?", a: "The French Open", d: "medium" },
      { q: "How many players per side are on the mat in kabaddi?", a: "Seven", d: "medium" },
      { q: "Roughly how long is a marathon in kilometres?", a: "About 42 km", d: "medium" },
      { q: "Who has scored 100 international centuries?", a: "Sachin Tendulkar", d: "medium" },
      { q: "Which bowler took 800 Test wickets?", a: "Muttiah Muralitharan", d: "hard" },
      { q: "Who has won the most Olympic gold medals?", a: "Michael Phelps", d: "hard" },
      { q: "Which city hosted the first modern Olympics in 1896?", a: "Athens", d: "hard" },
      { q: "How many Grand Slam singles titles did Rafael Nadal win?", a: "22", d: "hard" },
      { q: "Which country has won the most FIFA World Cups?", a: "Brazil", d: "hard" },
      { q: "Which Indian became world chess champion in 2024?", a: "D. Gukesh", d: "hard" },
      { q: "What is the maximum break in snooker?", a: "147", d: "hard" },
    ],
  },
  {
    id: "sci",
    label: "Science & tech",
    tone: "pink",
    questions: [
      { q: "Who co-founded Microsoft with Paul Allen?", a: "Bill Gates", d: "easy" },
      { q: "Which company makes the iPhone?", a: "Apple", d: "easy" },
      { q: "What does 'www' stand for?", a: "World Wide Web", d: "easy" },
      { q: "What is the closest star to Earth?", a: "The Sun", d: "easy" },
      { q: "How many planets are in our solar system?", a: "Eight", d: "easy" },
      { q: "Which vitamin do we get from sunlight?", a: "Vitamin D", d: "easy" },
      { q: "Which planet is famous for its rings?", a: "Saturn", d: "easy" },
      { q: "What is the largest organ of the human body?", a: "The skin", d: "easy" },
      { q: "What force keeps us on the ground?", a: "Gravity", d: "easy" },
      { q: "Which gas makes up most of the air?", a: "Nitrogen", d: "easy" },
      { q: "Who founded Facebook?", a: "Mark Zuckerberg", d: "easy" },
      { q: "What does CPU stand for?", a: "Central Processing Unit", d: "easy" },
      { q: "What is H2O more commonly known as?", a: "Water", d: "easy" },
      { q: "What is the chemical formula for table salt?", a: "NaCl", d: "medium" },
      { q: "Which planet is closest to the Sun?", a: "Mercury", d: "medium" },
      { q: "Who invented the telephone?", a: "Alexander Graham Bell", d: "medium" },
      { q: "What does DNA stand for?", a: "Deoxyribonucleic acid", d: "medium" },
      { q: "Which part of the cell contains DNA?", a: "The nucleus", d: "medium" },
      { q: "What is the process plants use to make food from sunlight?", a: "Photosynthesis", d: "medium" },
      { q: "What is the largest bone in the human body?", a: "The femur", d: "medium" },
      { q: "Which blood cells carry oxygen?", a: "Red blood cells", d: "medium" },
      { q: "Roughly how fast does light travel?", a: "About 300,000 km per second", d: "medium" },
      { q: "What is the atomic number of carbon?", a: "6", d: "hard" },
      { q: "Who proposed the three laws of planetary motion?", a: "Johannes Kepler", d: "hard" },
      { q: "What is the most abundant element in the universe?", a: "Hydrogen", d: "hard" },
      { q: "Who discovered penicillin?", a: "Alexander Fleming", d: "hard" },
      { q: "What is the SI unit of electrical resistance?", a: "The ohm", d: "hard" },
      { q: "What does HTTP stand for?", a: "HyperText Transfer Protocol", d: "hard" },
      { q: "What is the pH of pure water?", a: "7", d: "hard" },
      { q: "Who is credited with inventing the World Wide Web?", a: "Tim Berners-Lee", d: "hard" },
      { q: "Which planet has the longest day?", a: "Venus", d: "hard" },
      { q: "What is the chemical symbol for potassium?", a: "K", d: "hard" },
    ],
  },
];

export const DEFAULT_PACK_IDS = quizPacks.map((p) => p.id);

export function quizPool(packIds: string[], difficulty: DifficultySetting = "mix") {
  const seen = new Set<string>();
  const out: QuizQuestion[] = [];
  for (const pack of quizPacks) {
    if (!packIds.includes(pack.id)) continue;
    for (const item of pack.questions) {
      if (difficulty !== "mix" && item.d !== difficulty) continue;
      if (seen.has(item.q)) continue;
      seen.add(item.q);
      out.push(item);
    }
  }
  return out;
}
